"""LaTeX tables for the paper.  Every number is read from experiments/results;
formatting only.  Percent changes are exp(log contrast) - 1; intervals are the
95% fixed-design Student-t intervals over countries stored as `ci`, except
retention (paired stratified percentile bootstrap, `judge_gain_retained_ci`) and
the dish-mix split (pool-cluster bootstrap)."""
import json
import math
import os

from common import FIG, GEN_NAME, GENS, READERS, RD_NAME, RES, SC_NAME, SCORERS, load, pct, style

OUT = os.path.join(FIG, "tables")
os.makedirs(OUT, exist_ok=True)
SENS = json.load(open(os.path.join(RES, "sensitivity.json")))
DM = json.load(open(os.path.join(RES, "posthoc", "dish_mix_decomposition.json")))["cells"]
FAMS = ("stk", "mmr", "dpp")
FAM_TEX = {"topk": "top-$k$", "stk": "STK", "mmr": "MMR", "dpp": "DPP"}
PARAM_TEX = {"stk": "$c={}$", "mmr": "$\\lambda={}$", "dpp": "$\\alpha={}$"}


def n(x, nd=1, sign=True):
    s = f"{x:+.{nd}f}" if sign else f"{x:.{nd}f}"
    return "$" + s.replace("-", "-") + "$"


def vci(v, ci, f=pct, nd=1, sign=True):
    lo, hi = f(ci[0]), f(ci[1])
    return (f"{n(f(v), nd, sign)}\\,{{\\scriptsize$[{lo:+.{nd}f}, {hi:+.{nd}f}]$}}"
            if sign else
            f"{n(f(v), nd, False)}\\,{{\\scriptsize$[{lo:.{nd}f}, {hi:.{nd}f}]$}}")


def ident(x):
    return x


def write(name, body):
    with open(os.path.join(OUT, name), "w") as fh:
        fh.write("% generated by paper/figures/scripts/make_tables.py -- do not edit\n" + body)
    print("wrote", name)


def cell_name(g, s):
    return f"{GEN_NAME[g]} & {SC_NAME[s]}"


# ---- Table 1: top-16 vs random-16 diversity, DINOv2 and three tag readers ----
rows = []
for g in GENS:
    for s in SCORERS:
        emb = load("real", g)["a3__" + s]["chosen_on_tuning"]["topk"]["evaluation"]["emb_delta"]
        cells = [vci(emb["mean"], emb["ci"])]
        for rd, rdir in READERS:
            e = load(rdir, g)["a1__" + s]["raw"]
            cells.append(vci(e["mean_delta"], e["marginal"]["ci"]))
        rule = "yes" if SENS["diversity_robust"][f"{g}|{s}"] else "no"
        rows.append(cell_name(g, s) + " & " + " & ".join(cells) + f" & {rule} \\\\")
write("tab1_diversity.tex", "\n".join([
    "\\begin{tabular}{llccccc}", "\\toprule",
    " & & DINOv2 Vendi & \\multicolumn{3}{c}{Dish-label Vendi (reader)} & CI $<0$ under \\\\",
    "\\cmidrule(lr){4-6}",
    "Generator & Scorer & (reader-free) & " + " & ".join(RD_NAME[r] for r, _ in READERS)
    + " & all 3 readers \\\\", "\\midrule", *rows, "\\bottomrule", "\\end{tabular}", ""]))


# ---- Table 2 / appendix: A3 re-selection vs top-16, per selector -> judge cell ----
# Two stacked panels so each fits the 5.5in text width: (a) the registered A3
# quantities under the pre-registered reader; (b) the same selected images read by
# the reader-free DINOv2 measure and the two sensitivity readers (post hoc).
def a3_table(sc, fname):
    judge = SC_NAME[[s for s in SCORERS if s != sc][0]]
    ra, rb = [], []
    for gi, g in enumerate(GENS):
        a = load("real", g)["a3__" + sc]
        claims = load("real", g)["claims__" + sc]["A3"]
        if gi:
            ra.append("\\midrule")
            rb.append("\\midrule")
        for fi, fam in enumerate(FAMS):
            ch = a["chosen_on_tuning"][fam]
            vt = ch["vs_topk"]
            key = f"{fam}|{ch['param']}"
            lead = [GEN_NAME[g] if fi == 0 else "",
                    f"{FAM_TEX[fam]} ({PARAM_TEX[fam].format(ch['param'])})"]
            q = load("real", g)["a3__" + sc]["curves_vs_topk"][key]["delta"]
            ra.append(" & ".join(lead + [
                f"${ch['evaluation']['gain_judge']['mean']:.3f}$ / ${vt['topk_judge_gain']['mean']:.3f}$",
                vci(100 * vt["judge_gain_retained"], [100 * c for c in vt["judge_gain_retained_ci"]],
                    f=ident, sign=False),
                vci(vt["raw_gain_judge"]["mean"], vt["raw_gain_judge"]["ci"], f=ident, nd=3),
                vci(q["mean"], q["ci"]),
                f"${claims['p_holm']:.3f}$" if fam == claims["family"] else "--"]) + " \\\\")
            cells = lead + [vci(vt["emb_delta"]["mean"], vt["emb_delta"]["ci"])]
            for rd, rdir in READERS[1:]:
                d = load(rdir, g)["a3__" + sc]["curves_vs_topk"][key]["delta"]
                cells.append(vci(d["mean"], d["ci"]))
            rb.append(" & ".join(cells) + " \\\\")
    write(fname, "\n".join([
        "\\begin{tabular}{llccccc}", "\\toprule",
        "\\multicolumn{7}{l}{\\textit{(a) Registered A3 quantities, pre-registered reader (Qwen2.5-VL)}} \\\\",
        f" & & {judge} gain, SD & Retention, & Raw {judge} & Dish-label & A3 \\\\",
        "Gen. & Method & sel.\\ / top-16 & \\% of top-16 & $\\Delta$ vs top-16 & vs top-16, \\% & Holm $p$ \\\\",
        "\\midrule", *ra, "\\bottomrule", "\\end{tabular}", "", "\\vspace{4pt}", "",
        "\\begin{tabular}{llccc}", "\\toprule",
        "\\multicolumn{5}{l}{\\textit{(b) Same selected images: DINOv2 (registered secondary) and sensitivity readers (post hoc)}} \\\\",
        " & & DINOv2 Vendi & \\multicolumn{2}{c}{Dish-label Vendi vs top-16, \\%} \\\\",
        "\\cmidrule(lr){4-5}",
        "Gen. & Method & vs top-16, \\% & " + " & ".join(RD_NAME[r] for r, _ in READERS[1:]) + " \\\\",
        "\\midrule", *rb, "\\bottomrule", "\\end{tabular}", ""]))


a3_table("pickscore", "tab2_a3_primary.tex")
a3_table("imagereward", "tabA_a3_reverse.tex")

# ---- Appendix: A3 re-tuned under each sensitivity reader (sensitivity only) ----
rows = []
for rd, rdir in READERS[1:]:
    for g in GENS:
        for s in SCORERS:
            c = load(rdir, g)["claims__" + s]["A3"]
            ok = c.get("rule_met_sensitivity_only", False)
            rows.append(f"{RD_NAME[rd]} & {cell_name(g, s)} & {FAM_TEX[c['family']]} "
                        f"({PARAM_TEX[c['family']].format(c['param'])}) & "
                        + vci(c["delta_gain"]["mean"], c["delta_gain"]["ci"]) + " & "
                        + f"${100 * c['judge_gain_retained']:.1f}$ & ${c['p_holm']:.3f}$ & "
                        + ("yes" if ok else "no") + " \\\\")
write("tabA_retune.tex", "\n".join([
    "\\begin{tabular}{llllcccc}", "\\toprule",
    " & & & Family & Dish-label Vendi & Retention, & & Rule met \\\\",
    "Reader & Generator & Selector & (re-tuned) & vs top-16, \\% & \\% & Holm $p$ & (sensitivity) \\\\",
    "\\midrule", *rows, "\\bottomrule", "\\end{tabular}", ""]))

# ---- Appendix: verifier and tagger diagnostics per reader ----
rows = []
for rd, rdir in READERS:
    for g in GENS:
        r = load(rdir, g)["r1__pickscore"]
        vd, td = r["verifier_diagnostics"], r["tagger_diagnostics"]
        rows.append(f"{RD_NAME[rd]} & {GEN_NAME[g]} & ${vd['auc_true_vs_decoy']:.3f}$ & "
                    f"${100 * vd['forced_choice_keep_rate']:.1f}$ & ${100 * td['resolved_rate']:.1f}$ \\\\")
write("tabA_verifier.tex", "\n".join([
    "\\begin{tabular}{llccc}", "\\toprule",
    " & & Verifier AUC & Forced-choice & Tagger \\\\",
    "Reader & Generator & (true vs decoy) & keep, \\% & resolved, \\% \\\\",
    "\\midrule", *rows, "\\bottomrule", "\\end{tabular}", ""]))


# ---- Appendix: modal reader label per country, PickScore candidate pools ----
def tex_label(x):
    if any(ord(ch) > 0x2E7F for ch in x):     # CJK script: pdflatex cannot set it
        return "\\textit{(Japanese-script entry)}"
    return x.replace("&", "\\&").replace("_", "\\_")


rows = []
for g in GENS:
    countries = sorted(load("real", g)["rep__pickscore"]["by_country"])
    for c in countries:
        cells = []
        for rd, rdir in READERS:
            v = load(rdir, g)["rep__pickscore"]["by_country"].get(c) or {}
            cells.append(f"{tex_label(v['modal_dish'])} ({100 * v['modal_share_pool']:.0f}\\%)"
                         if v.get("modal_dish") else "n/a")
        rows.append(f"{GEN_NAME[g]} & {c} & " + " & ".join(cells) + " \\\\")
    rows.append("\\midrule")
rows = rows[:-1]
write("tabA_modal.tex", "\n".join([
    "\\begin{tabular}{llp{3.2cm}p{3.2cm}p{3.2cm}}", "\\toprule",
    "Generator & Country & " + " & ".join(RD_NAME[r] for r, _ in READERS) + " \\\\",
    "\\midrule", *rows, "\\bottomrule", "\\end{tabular}", ""]))

# ---- Appendix: R1 estimability (why A1 is unavailable) ----
rows = []
for g in GENS:
    for s in SCORERS:
        d = load("real", g)
        a1, gap = d["a1__" + s], d["r1__" + s]["verified"]["gap"]
        cond = a1["conditional"]
        rows.append(cell_name(g, s) + f" & {gap['n']}/{gap['n_pools_total']} & "
                    f"{gap['reason'].replace('no estimable pool for ', '')} & "
                    f"{cond['n_estimable']}/{a1['n_pools_total']} \\\\")
write("tabA_r1.tex", "\n".join([
    "\\begin{tabular}{llcp{5.2cm}c}", "\\toprule",
    " & & \\multicolumn{2}{c}{R1 known-label gap (verified)} & Conditional endpoint \\\\",
    "\\cmidrule(lr){3-4}",
    "Generator & Scorer & Pools estimable & Countries with no estimable pool & pools estimable \\\\",
    "\\midrule", *rows, "\\bottomrule", "\\end{tabular}", ""]))

# ---- Appendix: dish-mix decomposition (post hoc) ----
rows = []
for g in GENS:
    for s in SCORERS:
        for rd, _ in READERS:
            c = DM[f"{g}/{s}/{rd}"]
            rows.append(f"{GEN_NAME[g]} & {SC_NAME[s]} & {RD_NAME[rd]} & "
                        + " & ".join(vci(100 * c[t]["est"], [100 * x for x in c[t]["ci"]], f=ident)
                                     for t in ("total", "composition", "within")) + " \\\\")
write("tabA_dishmix.tex", "\n".join([
    "\\begin{tabular}{lllccc}", "\\toprule",
    "Generator & Scorer & Reader & Q4$-$Q1 total & Composition & Within-dish remainder \\\\",
    "\\midrule", *rows, "\\bottomrule", "\\end{tabular}", ""]))

# ---- Appendix: repetition (descriptive) ----
rows = []
for g in GENS:
    for s in SCORERS:
        r = load("real", g)["rep__" + s]
        nc = len(r["by_country"])
        rows.append(cell_name(g, s) + " & "
                    + vci(r["mean_repetition_excess"], r["repetition_ci"], f=ident, nd=3)
                    + f" & {r['n_countries_positive']}/{nc} & "
                    + vci(r["mean_repetition_excess_matched"], r["repetition_matched_ci"], f=ident, nd=3)
                    + f" & {r['n_countries_positive_matched']}/{nc} & "
                    + vci(r["mean_modal_share_excess"], r["modal_share_ci"], f=ident, nd=3) + " \\\\")
write("tabA_repetition.tex", "\n".join([
    "\\begin{tabular}{llccccc}", "\\toprule",
    " & & Jaccard excess & Countries & Cardinality-matched & Countries & Modal-share \\\\",
    "Generator & Scorer & (top-16 $-$ random) & $>0$ & Jaccard excess & $>0$ & excess \\\\",
    "\\midrule", *rows, "\\bottomrule", "\\end{tabular}", ""]))

# ---- Appendix: matched dose comparison k = 16 vs 32 (descriptive, post hoc) ----
rows = []
for g in GENS:
    for s in SCORERS:
        dr = load("real", g)["a1__" + s]["dose_response_summary"]
        d16, d32 = dr["16"], dr["32"]
        v = d32["vs_primary_k"]
        rows.append(cell_name(g, s) + " & " + vci(d16["mean_log_contrast"], d16["ci"]) + " & "
                    + vci(d32["mean_log_contrast"], d32["ci"]) + " & "
                    + vci(v["mean_diff"], v["ci"], f=ident, nd=3) + " \\\\")
write("tabA_dose.tex", "\n".join([
    "\\begin{tabular}{llccc}", "\\toprule",
    " & & \\multicolumn{2}{c}{Dish-label Vendi vs random-$k$, \\%} & $k{=}32$ minus $k{=}16$ \\\\",
    "\\cmidrule(lr){3-4}",
    "Generator & Scorer & $k=16$ & $k=32$ & (log units) \\\\",
    "\\midrule", *rows, "\\bottomrule", "\\end{tabular}", ""]))

# ---- Appendix (amendment 7, E8): readers and scorers on WorldCuisines real photos ----
E8 = json.load(open(os.path.join(RES, "a7", "realimg", "e8.json")))
SC4 = ("pickscore", "imagereward", "laion_aes", "hpsv21")
SC4_NAME = {**SC_NAME, "laion_aes": "LAION-Aes", "hpsv21": "HPSv2.1"}
rows = []
for rd, _ in READERS:
    r = E8["readers"][rd]
    a, b, c = r["e8a"], r["e8b"], r["e8c"]
    rows.append(f"{RD_NAME[rd]} & {a['all']['dish_acc']:.3f} & {a['gt_in_cspace']['dish_acc']:.3f} & "
                f"{a['all']['country_acc']:.3f} & "
                + vci(b["acc"], b["ci"], f=ident, nd=3, sign=False)
                + f" & {c['spearman']:.2f} & {n(c['mean_log_ratio'], 2)} & {c['contrast_slope']:.2f}"
                f" & {c['contrast_sign_agree_gt10']:.2f} \\\\")
write("tabA_e8_readers.tex", "\n".join([
    "\\begin{tabular}{lcccccccc}", "\\toprule",
    " & \\multicolumn{2}{c}{Dish accuracy} & Country & Forced-choice & \\multicolumn{4}{c}{Rarefied label Vendi, reader vs dataset labels} \\\\",
    "\\cmidrule(lr){2-3}\\cmidrule(lr){6-9}",
    "Reader & all & in CSpace & accuracy & accuracy & Spearman & log ratio & slope & sign agree$^\\dagger$ \\\\",
    "\\midrule", *rows, "\\bottomrule", "\\end{tabular}", ""]))
rows = []
for rd, _ in READERS:
    d = E8["readers"][rd]["e8d"]
    rows.append(RD_NAME[rd] + " & " + " & ".join(
        vci(100 * d[s]["top_minus_bottom"], [100 * x for x in d[s]["top_minus_bottom_ci"]], f=ident)
        for s in SC4) + " \\\\")
write("tabA_e8_keep.tex", "\n".join([
    "\\begin{tabular}{lcccc}", "\\toprule",
    "Reader & " + " & ".join(SC4_NAME[s] for s in SC4) + " \\\\",
    "\\midrule", *rows, "\\bottomrule", "\\end{tabular}", ""]))

# ---- Appendix E11 (post hoc): top-quarter selection on the labelled photographs ----
E11P = os.path.join(RES, "extra", "e11", "e11.json")
if os.path.exists(E11P):
    E11 = json.load(open(E11P))
    E11_COLS = ("dataset", "qwen", "pixtral", "siglip", "emb_dinov2", "emb_siglip")
    rows = []
    for s in SC4:
        c = E11["scorers"][s]["pooled"]
        nul = E11["between_dish_score_variance_share_null"][s]
        rows.append(SC4_NAME[s] + " & " + " & ".join(vci(c[m]["log_delta"], c[m]["ci"]) for m in E11_COLS)
                    + f" & {nul['eta2']:.2f} ({nul['null_mean']:.2f}) \\\\")
    write("tabA_e11.tex", "\n".join([
        "\\begin{tabular}{lccccccc}", "\\toprule",
        " & Dataset & \\multicolumn{3}{c}{Reader labels} & \\multicolumn{2}{c}{Embedding} & Between-dish \\\\",
        "\\cmidrule(lr){3-5}\\cmidrule(lr){6-7}",
        "Scorer & labels & " + " & ".join(RD_NAME[r] for r, _ in READERS)
        + " & DINOv2 & SigLIP & score share \\\\",
        "\\midrule", *rows, "\\bottomrule", "\\end{tabular}", ""]))

# ---- Appendix (amendment 7, E9/E10): four scorers x four generators ----
A7_GENS = ("sdxl", "flux-schnell", "pixart-sigma", "sd35m")
A7_GEN_NAME = {**GEN_NAME, "pixart-sigma": "PixArt-$\\Sigma$", "sd35m": "SD3.5-M"}
A7_RD = tuple((rd, os.path.join("a7", rd)) for rd, _ in READERS)


# ---- Appendix (post hoc E12): frozen selections re-measured in SigLIP space ----
E12_KEY = {"pickscore": "a3__pickscore", "imagereward": "a3__imagereward",
           "laion_aes": "a3x__laion_aes__pickscore", "hpsv21": "a3x__hpsv21__pickscore"}
e12_rows = []
for g in ("sdxl", "flux-schnell", "pixart-sigma", "sd35m"):
    fp = os.path.join(RES, "extra", "e12", g + ".json")
    if not os.path.exists(fp):
        continue
    E12 = json.load(open(fp))
    for s in SC4:
        r = E12.get(E12_KEY[s])
        if r is None:
            continue
        cells = []
        t = r["evaluation"]["topk"]
        cells += [n(pct(t["dinov2"]["mean"])), vci(t["siglip"]["mean"], t["siglip"]["ci"])]
        for fam in FAMS:
            v = r["vs_topk"].get(fam)
            cells += (["--", "--"] if v is None else
                      [n(pct(v["dinov2"]["mean"])), vci(v["siglip"]["mean"], v["siglip"]["ci"])])
        e12_rows.append(f"{A7_GEN_NAME[g]} & {SC4_NAME[s]} & " + " & ".join(cells) + " \\\\")
if e12_rows:
    write("tabA_e12.tex", "\n".join([
        "\\begin{tabular}{llcccccccc}", "\\toprule",
        " & & \\multicolumn{2}{c}{Top-16 vs.\\ random-16} & \\multicolumn{2}{c}{STK vs.\\ top-16}"
        " & \\multicolumn{2}{c}{MMR vs.\\ top-16} & \\multicolumn{2}{c}{DPP vs.\\ top-16} \\\\",
        "\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}\\cmidrule(lr){7-8}\\cmidrule(lr){9-10}",
        "Generator & Selector & DINOv2 & SigLIP & DINOv2 & SigLIP & DINOv2 & SigLIP & DINOv2 & SigLIP \\\\",
        "\\midrule", *e12_rows, "\\bottomrule", "\\end{tabular}", ""]))

# ---- Appendix (post hoc): tuned STK vs tuned DPP, paired; retention in native units ----
fp_sd = os.path.join(RES, "extra", "stk_vs_dpp.json")
fp_nu = os.path.join(RES, "extra", "native_units.json")
if os.path.exists(fp_sd) and os.path.exists(fp_nu):
    SD = json.load(open(fp_sd))["cells"]
    NU = {(c["generator"], c["selector"]): c for c in json.load(open(fp_nu))["cells"]}
    sd_rows = []
    for c in SD:
        g, s = c["generator"], c["selector"]
        t = c["tuned"]["dpp"]
        nu = NU[(g, s)]["families"]
        ret = []
        for fam in ("stk", "dpp"):
            r = nu[fam]["native"]
            ret.append(vci(r["retained"], r["retained_ci"], f=lambda x: 100 * x, sign=False))
        sd_rows.append(" & ".join([
            A7_GEN_NAME[g], f"{SC_NAME[s]} $\\to$ {SC_NAME[c['judge']]}",
            f"$c={c['chosen']['stk']}$ / $\\alpha={c['chosen']['dpp']:g}$",
            vci(t["gain_judge"]["mean"], t["gain_judge"]["ci"], f=ident, nd=3),
            vci(t["emb_delta"]["mean"], t["emb_delta"]["ci"]),
            vci(t["delta"]["mean"], t["delta"]["ci"]), *ret]) + " \\\\")
    write("tabA_stkdpp.tex", "\n".join([
        "\\begin{tabular}{lllccccc}", "\\toprule",
        " & & & \\multicolumn{3}{c}{Tuned STK $-$ tuned DPP} & \\multicolumn{2}{c}{Retained (native units, \\%)} \\\\",
        "\\cmidrule(lr){4-6}\\cmidrule(lr){7-8}",
        "Generator & Selector $\\to$ judge & Parameters & Judge gain (SD) & DINOv2 (\\%) & Dish label (\\%) & STK & DPP \\\\",
        "\\midrule", *sd_rows, "\\bottomrule", "\\end{tabular}", ""]))

def a7_have(g):
    return all(os.path.exists(os.path.join(RES, d, g + ".json")) for _, d in A7_RD)


def a7_topk_emb(r, s):
    key = f"a3__{s}" if s in SCORERS else f"a3x__{s}__pickscore"
    return r[key]["chosen_on_tuning"]["topk"]["evaluation"]["emb_delta"]


A7 = [g for g in A7_GENS if a7_have(g)]
div_rows, rec_rows, stk_rows = [], [], []
for g in A7:
    for s in SC4:
        rq = load(A7_RD[0][1], g)
        emb = a7_topk_emb(rq, s)
        cells, below = [vci(emb["mean"], emb["ci"])], []
        for rd, d in A7_RD:
            e = load(d, g)["a1__" + s]["raw"]
            cells.append(vci(e["mean_delta"], e["marginal"]["ci"]))
            below.append(e["marginal"]["ci"][1] < 0)
        div_rows.append(f"{A7_GEN_NAME[g]} & {SC4_NAME[s]} & " + " & ".join(cells)
                        + f" & {'yes' if all(below) else 'no'} \\\\")
        rc = []
        for rd, d in A7_RD:
            q = load(d, g)["r1__" + s]["verifier_keep_by_score_quartile"]
            rc.append(vci(100 * q["top_minus_bottom"], [100 * x for x in q["ci"]], f=ident))
        rec_rows.append(f"{A7_GEN_NAME[g]} & {SC4_NAME[s]} & " + " & ".join(rc) + " \\\\")
        for j in ([x for x in SCORERS if x != s] if s in SCORERS else SCORERS):
            key = f"a3__{s}" if s in SCORERS else f"a3x__{s}__{j}"
            c = rq[key]["chosen_on_tuning"]["stk"]
            v = c["vs_topk"]
            stk_rows.append(f"{A7_GEN_NAME[g]} & {SC4_NAME[s]} & {SC4_NAME[j]} & $c={c['param']}$ & "
                            + (vci(100 * v["judge_gain_retained"],
                                   [100 * x for x in v["judge_gain_retained_ci"]], f=ident, sign=False)
                               if math.isfinite(v["judge_gain_retained"]) else "n/e")
                            + " & " + vci(v["emb_delta"]["mean"], v["emb_delta"]["ci"])
                            + " & " + vci(v["delta"]["mean"], v["delta"]["ci"]) + " \\\\")
    if g != A7[-1]:
        for rows in (div_rows, rec_rows, stk_rows):
            rows.append("\\midrule")
if A7:
    write("tabA_a7_div.tex", "\n".join([
        "\\begin{tabular}{llccccc}", "\\toprule",
        " & & DINOv2 Vendi & \\multicolumn{3}{c}{Dish-label Vendi (reader)} & CI $<0$ under \\\\",
        "\\cmidrule(lr){4-6}",
        "Generator & Scorer & (reader-free) & " + " & ".join(RD_NAME[r] for r, _ in A7_RD)
        + " & all 3 readers \\\\", "\\midrule", *div_rows, "\\bottomrule", "\\end{tabular}", ""]))
    write("tabA_a7_rec.tex", "\n".join([
        "\\begin{tabular}{llccc}", "\\toprule",
        " & & \\multicolumn{3}{c}{Keep rate Q4$-$Q1, points (reader)} \\\\", "\\cmidrule(lr){3-5}",
        "Generator & Scorer & " + " & ".join(RD_NAME[r] for r, _ in A7_RD) + " \\\\",
        "\\midrule", *rec_rows, "\\bottomrule", "\\end{tabular}", ""]))
    write("tabA_a7_stk.tex", "\n".join([
        "\\begin{tabular}{llllccc}", "\\toprule",
        " & & & STK & Retention & \\multicolumn{2}{c}{Change vs top-16, \\%} \\\\",
        "\\cmidrule(lr){6-7}",
        "Generator & Selector & Judge & (tuned) & \\% & DINOv2 & Qwen2.5-VL label \\\\",
        "\\midrule", *stk_rows, "\\bottomrule", "\\end{tabular}", ""]))

# ---- Appendix (post hoc): E13 more re-selector families ----
fp13 = os.path.join(RES, "extra", "e13", "e13.json")
if os.path.exists(fp13):
    E13 = json.load(open(fp13))["cells"]
    FAM13 = [("stk", "STK", "$c={:g}$"), ("dpp", "DPP", "$\\alpha={:g}$"),
             ("thr", "Top-$q$ random", "$q={:g}$"), ("fl", "Facility loc.", "$\\beta={:g}$"),
             ("vendi", "Greedy Vendi", "$\\gamma={:g}$"),
             ("kcenter", "MMR, ext.\\ grid", "$\\lambda={:.2f}$")]
    rows13 = []
    for i, c in enumerate(E13):
        fams = c["families"]
        for j, (fam, name, ptex) in enumerate(FAM13):
            e = fams[fam]
            p = e["param"] / (1 + e["param"]) if fam == "kcenter" else e["param"]
            ret = e["retained_pct"]
            head = (f"{A7_GEN_NAME[c['generator']]} & {SC_NAME[c['selector']]} $\\to$ {SC_NAME[c['judge']]}"
                    if j == 0 else " & ")
            rows13.append(" & ".join([head, name, ptex.format(p),
                                      vci(e["emb_delta"]["mean"], e["emb_delta"]["ci"]),
                                      vci(e["delta"]["mean"], e["delta"]["ci"]),
                                      vci(ret["value"], ret["ci"], f=ident, sign=False)]) + " \\\\")
        if i != len(E13) - 1:
            rows13.append("\\midrule")
    write("tabA_e13.tex", "\n".join([
        "\\begin{tabular}{llllccc}", "\\toprule",
        " & & & Tuned & \\multicolumn{2}{c}{Change vs random-16, \\%} & Retained \\\\",
        "\\cmidrule(lr){5-6}",
        "Generator & Selector $\\to$ judge & Family & parameter & DINOv2 & Qwen2.5-VL label & \\% \\\\",
        "\\midrule", *rows13, "\\bottomrule", "\\end{tabular}", ""]))

# ---- Appendix (post hoc): E14 best-of-N selection intensity ----
fp14 = os.path.join(RES, "extra", "e14", "e14.json")
if os.path.exists(fp14):
    E14 = json.load(open(fp14))["results"]
    rows14 = []
    for g in ("sdxl", "flux-schnell", "pixart-sigma", "sd35m"):
        for s in ("pickscore", "imagereward", "laion_aes", "hpsv21"):
            r = E14[g][s]
            b = r["by_N"]
            rows14.append(" & ".join([A7_GEN_NAME[g] if s == "pickscore" else "", SC4_NAME[s],
                                      *[n(pct(b[str(N)]["emb_delta"]["mean"])) for N in (20, 32, 64)],
                                      vci(r["slope_per_doubling"]["mean"], r["slope_per_doubling"]["ci"]),
                                      n(b["64"]["gain_judge"]["mean"], 2, False)]) + " \\\\")
        if g != "sd35m":
            rows14.append("\\midrule")
    write("tabA_e14.tex", "\n".join([
        "\\begin{tabular}{llccccc}", "\\toprule",
        " & & \\multicolumn{3}{c}{DINOv2 Vendi vs random-16, \\%} & Change per & Judge gain \\\\",
        "\\cmidrule(lr){3-5}",
        "Generator & Scorer & $N=20$ & $N=32$ & $N=64$ & doubling of $N$, \\% & at $N=64$ (SD) \\\\",
        "\\midrule", *rows14, "\\bottomrule", "\\end{tabular}", ""]))
